//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV
    {
        public string MSSV { get; set; }
        public string NameSV { get; set; }
        public Nullable<double> DTB { get; set; }
        public Nullable<int> ID_Lop { get; set; }
        public Nullable<bool> Anh { get; set; }
        public Nullable<bool> HocBa { get; set; }
        public Nullable<bool> CCNN { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        public virtual LOP LOP { get; set; }
    }
}
